# modulo -> (area, [mappe], fase, descrizione del modulo)
# mappe: 1..10 come nell'Atlante; [] = fuori dalle dieci mappe
M = {
 # ── Spina dorsale ───────────────────────────────────────────────
 'app.js': ('Nucleo', [1,2,3], 'sempre', "Il nucleo del renderer: appState, provider AI, fetchModelAPI, fonti, router della generazione, avvio."),
 'preload.js': ('Nucleo', [1,2,10], 'sempre', "Il ponte contextBridge: l'unico passaggio fra la pagina e il processo Electron."),
 'main.js': ('Nucleo', [1,2,10], 'sempre', "Il processo principale Electron: finestra, IPC, disco, chiamate HTTP ai provider, avvio dei server LAN."),
 'storageAdapter.js': ('Nucleo', [1,10], 'sempre', "Finge electronAPI quando l'app non gira in Electron (iPadOS, web): chiavi sicure e storage."),
 'infomaniak_bridge.js': ('Nucleo', [2,8], 'generazione', "Traduce il payload in stile Gemini nel formato OpenAI di Infomaniak."),
 'admin_prompts.js': ('Nucleo', [2,3], 'generazione', "Dashboard admin dei template di prompt e fillPromptTemplate, che li riempie."),
 'mappai-net-mode.js': ('Nucleo', [1,6], 'classe', "Interruttore «WiFi aula / Internet» condiviso dai wizard delle attività col QR."),
 'relay-client.js': ('Nucleo', [1,6], 'classe', "Client del relay per la variante web, quando la classe non è sulla stessa rete."),

 # ── Server LAN ──────────────────────────────────────────────────
 'live-server.js': ('Server LAN', [1,6], 'classe', "Server LAN di MappAI Live: serve la pagina allo studente, riceve le risposte, corregge."),
 'tutor-server.js': ('Server LAN', [1], 'classe', "Server LAN di «Chatta e Scrivi»: la chat tutor degli studenti passa di qui."),
 'collab-server.js': ('Server LAN', [1], 'classe', "Server LAN della Lavagna collaborativa."),
 'garden-server.js': ('Server LAN', [1], 'classe', "Server LAN del Knowledge Garden."),

 # ── Generazione ─────────────────────────────────────────────────
 'mappai-mm-extraction.js': ('Generazione', [3,5,9], 'generazione', "Il motore MindMap: Fase 1 macro-aree, Fase 3 rami, Fase 3.7 deepening."),
 'mappai-kg-extraction.js': ('Generazione', [3,5], 'generazione', "Il motore Knowledge Graph: single-pass, Community (GraphRAG), multi-pass."),
 'mappai-generation-support.js': ('Generazione', [3,5,9], 'generazione', "Gli aiutanti di ogni fase: cross-link, dedup, JSONL, prompt dei rami, arricchimento."),
 'mappai-mm-triage.js': ('Generazione', [3], 'generazione', "Il triage: una chiamata prima della Fase 1 decide quanto va approfondita la mappa."),
 'mappai-l1-checkpoint.js': ('Generazione', [3], 'generazione', "Il checkpoint delle macro-aree L1: le valida e le materializza prima dei rami."),
 'mappai-tree-sanitizer.js': ('Generazione', [3,5], 'generazione', "Ripara le anomalie strutturali dell'albero uscito dal modello (ID e livelli)."),
 'mappai-json-salvage.js': ('Generazione', [2,3,9], 'generazione', "Recupera il JSON rotto o troncato dell'AI invece di perdere tutta la risposta."),
 'mappai-anchor-core.js': ('Generazione', [3,5], 'generazione', "L'àncora, logica pura: riaggancia ogni nodo alle frasi vere della fonte e misura."),
 'mappai-anchor.js': ('Generazione', [3,5], 'generazione', "L'àncora applicata alla mappa vera, una volta a fine generazione, senza AI."),
 'mappai-deepen-core.js': ('Generazione', [3], 'generazione', "Il residuo della fonte e il verdetto anti-parafrasi della Fase 3.7."),
 'mappai-desc-fidelity.js': ('Generazione', [3,5], 'generazione', "Misura quanto una descrizione è ancorata alla fonte, contando le parole vere."),
 'mappai-judge-core.js': ('Generazione', [3,5], 'revisione', "Il giudice: che cosa si accetta di un verdetto sugli errori di senso."),
 'mappai-grounding-core.js': ('Generazione', [3,4], 'revisione', "Il terreno comune dei derivati: fatti approvati e stralci di fonte archiviati."),
 'mappai-enrich-core.js': ('Generazione', [3,4], 'revisione', "Il motore di ELABORA: copertura della fonte e arricchimento con citazioni."),
 'mappai-boilerplate-core.js': ('Generazione', [3], 'generazione', "Riconosce intestazioni e piè ripetuti nelle schede, per non farli entrare in mappa."),
 'mappai-questions-core.js': ('Generazione', [3,4], 'generazione', "Estrae dalla fonte le domande e gli esercizi già scritti dal libro."),
 'mappai-entity-backbone.js': ('Generazione', [5], 'revisione', "Diagnostica: la stessa entità spalmata su rami diversi."),
 'mappai-lenses.js': ('Generazione', [3], 'generazione', "Le lenti di estrazione: filtri semantici che guidano l'AI, iniettati nel focus."),
 'mappai-disciplines.js': ('Generazione', [3], 'generazione', "I profili disciplinari: la disciplina attiva entra nel prompt di sistema."),
 'mappai-relations.js': ('Generazione', [3,5], 'generazione', "La tassonomia delle relazioni: le sette famiglie di archi e i loro verbi."),
 'mappai-contextual-ai.js': ('Generazione', [5], 'revisione', "«Espandi con AI»: allarga un nodo con concetti presi da un testo o un PDF."),
 'mappai-generazione.js': ('Generazione', [3], 'generazione', "Il lucchetto: una generazione alla volta, e chi lo tiene."),
 'mappai-lavori.js': ('Generazione', [3,4], 'sempre', "L'indicatore dei lavori in corso nella barra in alto."),

 # ── Materiali ───────────────────────────────────────────────────
 'mappai-material-pipeline.js': ('Materiali', [4], 'materiali', "L'orchestratore di «Genera materiali»: configurazione, stima, esecuzione, esiti."),
 'mappai-pipeline-core.js': ('Materiali', [4], 'materiali', "La logica pura della pipeline materiali: che cosa si genera, in che ordine, a che costo."),
 'mappai-material-drafts.js': ('Materiali', [4], 'materiali', "Una rappresentazione unica delle bozze per giudice, editor ed export."),
 'mappai-material-review.js': ('Materiali', [4], 'revisione', "La revisione finale delle bozze normalizzate, in sola lettura."),
 'mappai-branch-synthesis.js': ('Materiali', [4], 'materiali', "«Sintesi di ramo»: un racconto con citazioni di un ramo intero."),
 'mappai-crea-quiz.js': ('Materiali', [4], 'materiali', "Il pannello che crea i quiz dentro CREA."),
 'mappai-doc-editor.js': ('Materiali', [4], 'materiali', "L'editor dei documenti già generati: quiz, flashcard, sintesi, foglio dei nodi."),
 'mappai-docedit-core.js': ('Materiali', [4], 'materiali', "Il modello puro dei documenti editabili."),
 'mappai-nodesheet-core.js': ('Materiali', [4], 'materiali', "Il modello del foglio dei nodi editabile."),
 'mappai-clona-core.js': ('Materiali', [4], 'materiali', "Clona un documento in una seconda copia editabile, col nome giusto."),
 'mappai-study-doc.js': ('Materiali', [4], 'materiali', "Il guscio comune dei documenti di studio esportati in PDF."),
 'mappai-study-export-core.js': ('Materiali', [4], 'materiali', "L'infrastruttura condivisa fra sintesi di ramo e dossier."),
 'mappai-doc-bar.js': ('Materiali', [4], 'materiali', "La barra del documento: una sola, per tutte le anteprime."),
 'mappai-doc-head.js': ('Materiali', [4], 'materiali', "La testata e il piè di pagina dei documenti, in un posto solo."),
 'mappai-print-dossier.js': ('Materiali', [4,5], 'materiali', "Stampa: note Markdown, etichette dei nodi, dossier PDF."),
 'mappai-print-layout.js': ('Materiali', [4], 'materiali', "I numeri del foglio flashcard: griglia, tagli, margini."),
 'mappai-quiz-print.js': ('Materiali', [4,6], 'materiali', "Costruisce le pagine stampabili di quiz, domande aperte e flashcard."),
 'mappai-visione.js': ('Materiali', [3,4], 'materiali', "Le fonti iconografiche: le immagini lette da Gemini entrano nei materiali."),
 'mappai-visione-core.js': ('Materiali', [3,4], 'materiali', "La logica pura delle immagini: che cosa si manda al modello e come torna."),
 'mappai-timeline.js': ('Materiali', [4], 'materiali', "La vista timeline cronologica generata con l'AI."),
 'mappai-timeline-core.js': ('Materiali', [4], 'materiali', "La logica pura della timeline: date, ordinamento, deduplica."),
 'mappai-latex.js': ('Materiali', [4], 'sempre', "Rendering delle formule con KaTeX dentro le schede."),
 'mappai-math.js': ('Materiali', [], 'sempre', "Utility matematiche pure estratte dal nucleo."),
 'mappai-text-utils.js': ('Materiali', [], 'sempre', "Utility di testo pure estratte dal nucleo."),

 # ── Revisione docente ───────────────────────────────────────────
 'mappai-review.js': ('Revisione', [5], 'revisione', "Il controllore della revisione docente: pipeline.json decide, appState è la sua cache."),
 'mappai-review-core.js': ('Revisione', [5], 'revisione', "Proposte, decisioni e commit recuperabile della revisione, senza DOM né AI."),
 'mappai-review-store.js': ('Revisione', [5,10], 'revisione', "La persistenza della revisione, solo nel processo principale."),
 'mappai-review-context.js': ('Revisione', [5], 'revisione', "Il contesto in sola lettura della revisione: etichette e colori risolti dalla mappa."),
 'mappai-correction-core.js': ('Revisione', [5], 'revisione', "Il modello dati delle correzioni annotate dal docente (ground truth)."),
 'mappai-correction-mode.js': ('Revisione', [5], 'revisione', "«Revisione mappa»: la superficie che raccoglie le correzioni annotate."),
 'mappai-structure-analyzer.js': ('Revisione', [5,9], 'revisione', "Analisi strutturale deterministica della mappa: god node, ponti, rami poveri."),
 'mappai-suggestions-panel.js': ('Revisione', [5], 'revisione', "Il pannello dei suggerimenti strutturali nella tab Struttura."),
 'mappai-meta-analysis.js': ('Revisione', [], 'classe', "Meta-analisi dei vault degli studenti per il feedback del docente."),
 'mappai-chat-analysis.js': ('Revisione', [], 'classe', "Metriche deterministiche sulle chat del tutor."),
 'mappai-elabora.js': ('Revisione', [4,5], 'revisione', "Il guscio di ELABORA: fonte e analisi affiancate, il co-docente."),
 'mappai-elabora-console.js': ('Revisione', [4], 'revisione', "ELABORA come console: la superficie, i passi, le scelte."),

 # ── Mappa e canvas ──────────────────────────────────────────────
 'mappai-d3-render.js': ('Mappa e canvas', [5,9], 'sempre', "Il motore di disegno D3: simulazione, nodi, archi, lenti, filtri."),
 'mappai-ui-canvas.js': ('Mappa e canvas', [5], 'sempre', "Il canvas e la barra laterale: overlay, clic sul nodo, scheda della fonte, layout."),
 'mappai-context-menu.js': ('Mappa e canvas', [5], 'sempre', "Il menu contestuale del nodo, il lightbox e il tocco."),
 'mappai-edit-modal.js': ('Mappa e canvas', [5], 'revisione', "Il modale che modifica un nodo: testo, colore, link, immagini."),
 'mappai-node-merge.js': ('Mappa e canvas', [5], 'revisione', "«Fondi con…» e «Cambia link»: le due operazioni che rifanno la struttura."),
 'mappai-node-styling.js': ('Mappa e canvas', [5], 'sempre', "Il ruolo strutturale del nodo diventa aspetto: keystone, ponte."),
 'mappai-merge-validate.js': ('Mappa e canvas', [5], 'revisione', "Unione di due grafi, cross-link con l'AI e validazione dei link."),
 'mappai-multiselect.js': ('Mappa e canvas', [5], 'revisione', "Selezione multipla di nodi e trascinamento di gruppo."),
 'mappai-undo.js': ('Mappa e canvas', [5], 'revisione', "Lo stack dell'annulla per le operazioni distruttive."),
 'mappai-search-finder.js': ('Mappa e canvas', [5], 'studio', "Il cerca-nella-mappa e il super finder su più vault."),
 'mappai-sidebar-resize.js': ('Mappa e canvas', [], 'sempre', "La maniglia che allarga la barra laterale."),
 'mappai-effort-view.js': ('Mappa e canvas', [5], 'studio', "L'overlay «Lavoro»: tinge i nodi secondo lo studio fatto."),
 'mappai-mastery-view.js': ('Mappa e canvas', [5], 'studio', "L'overlay «Padronanza»: tinge i nodi secondo quanto si sa."),
 'mappai-studio-view.js': ('Mappa e canvas', [5], 'studio', "La Vista studio: la mappa disposta per essere studiata, non per essere esplorata."),
 'mappai-studio-layouts.js': ('Mappa e canvas', [5], 'studio', "I motori di disposizione deterministici della Vista studio."),
 'mappai-studio-draw.js': ('Mappa e canvas', [5], 'studio', "Il disegno della Vista studio."),
 'mappai-vista-core.js': ('Mappa e canvas', [5,10], 'studio', "La vista di una mappa viaggia col suo vault: profilo, colori, disposizione."),
 'mappai-vista-ridotta.js': ('Mappa e canvas', [], 'generazione', "COSTRUISCI in forma ridotta: solo quel che serve a fare una mappa da una scheda."),
 'mappai-proiezione.js': ('Mappa e canvas', [], 'classe', "La proiezione alla LIM."),
 'mappai-proiezione-core.js': ('Mappa e canvas', [], 'classe', "La logica pura della proiezione."),

 # ── Vault e file ────────────────────────────────────────────────
 'mappai-vault-io.js': ('Vault e file', [10,3], 'sempre', "Salva e carica il vault Markdown: index.yaml, links.json, Nodi/*.md."),
 'mappai-vault-manager.js': ('Vault e file', [10], 'sempre', "L'elenco dei vault e il caricamento diretto di uno di essi."),
 'mappai-vaults-bus.js': ('Vault e file', [10], 'sempre', "«Le cartelle sono cambiate»: un canale solo per aggiornare gli elenchi."),
 'mappai-files-core.js': ('Vault e file', [10], 'sempre', "La logica pura dell'organizzazione dei file: percorsi, nomi, migrazioni."),
 'mappai-files-settings.js': ('Vault e file', [10], 'avvio', "La scelta della cartella madre «MappAI - file» e la migrazione dello storico."),
 'mappai-storage-lang.js': ('Vault e file', [10], 'sempre', "Autosave, progetti salvati e cambio lingua dell'interfaccia."),
 'mappai-errori.js': ('Vault e file', [9,10], 'sempre', "Il registro locale degli errori: si scrive su disco, non parte niente."),

 # ── Classe e attività live ──────────────────────────────────────
 'mappai-live-teacher.js': ('Classe e live', [6], 'classe', "L'hub di MappAI Live lato docente: le attività col QR."),
 'mappai-live-core.js': ('Classe e live', [6], 'classe', "La logica pura di Live: correzione delle risposte, punteggi, stato della sessione."),
 'mappai-live-reports.js': ('Classe e live', [6], 'classe', "I report HTML di Live: per domanda e per studente."),
 'mappai-live-classes.js': ('Classe e live', [6], 'classe', "Gli account classe: il registro delle credenziali su disco."),
 'mappai-scelta.js': ('Classe e live', [6], 'classe', "Le attività «a scelta»: dove si leggono i materiali e da dove partono."),
 'mappai-scelta-core.js': ('Classe e live', [6], 'classe', "La logica pura delle attività a scelta."),
 'mappai-scelta-view.js': ('Classe e live', [6], 'classe', "La superficie unica delle attività a scelta: telefono, modale, proiezione."),
 'mappai-collab-teacher.js': ('Classe e live', [], 'classe', "La Lavagna collaborativa lato docente."),
 'mappai-collab-core.js': ('Classe e live', [], 'classe', "La logica pura della Lavagna collaborativa."),
 'mappai-tutor-teacher.js': ('Classe e live', [], 'classe', "«Chatta e Scrivi» lato docente: wizard, dashboard, cap di spesa."),
 'mappai-tutor-core.js': ('Classe e live', [], 'classe', "La logica pura di «Chatta e Scrivi»."),
 'mappai-tutor-reports.js': ('Classe e live', [], 'classe', "Il report HTML di «Chatta e Scrivi»."),
 'mappai-timeline-teacher.js': ('Classe e live', [], 'classe', "L'attività Timeline di Live: wizard, dashboard, LIM."),
 'mappai-jigsaw.js': ('Classe e live', [], 'classe', "La modalità JIGSAW: ogni studente scrive solo il suo pezzo."),
 'mappai-teach-core.js': ('Classe e live', [], 'classe', "La logica pura della landing INSEGNA."),
 'mappai-landing-teach.js': ('Classe e live', [], 'classe', "La landing COSTRUISCI/INSEGNA: le tabelle dei file e delle attività."),
 'mappai-teacher-profile.js': ('Classe e live', [], 'avvio', "Il profilo dell'insegnante."),
 'mappai-user-profile.js': ('Classe e live', [], 'avvio', "I profili utente: classe, grado, preferenze."),

 # ── Studio e ripasso ────────────────────────────────────────────
 'mappai-study-session.js': ('Studio', [], 'studio', "La sessione di studio: configurazione, svolgimento, punteggi, report."),
 'mappai-study-bus.js': ('Studio', [], 'studio', "Il punto unico dove ogni attività registra il risultato."),
 'mappai-study-path.js': ('Studio', [], 'studio', "«Cosa studiare ora»: prerequisiti e rimedi in un pannello solo."),
 'mappai-learning-path.js': ('Studio', [], 'studio', "Un percorso breve montato con esercizi già approvati, senza generare."),
 'mappai-active-study.js': ('Studio', [], 'studio', "Il lanciatore delle attività di studio."),
 'mappai-active-study-core.js': ('Studio', [], 'studio', "Gli helper puri dello studio attivo: misura e confronto delle risposte."),
 'mappai-flashcards-sr.js': ('Studio', [], 'studio', "Flashcard e ripetizione dilazionata."),
 'mappai-mastery.js': ('Studio', [], 'studio', "Lo store della padronanza per pinpoint (Precision Teaching)."),
 'mappai-celeration.js': ('Studio', [], 'studio', "Il grafico dei progressi nel tempo."),
 'mappai-palace.js': ('Studio', [], 'studio', "Il Palazzo della Memoria: i rami diventano stanze."),
 'mappai-causal-chains.js': ('Studio', [], 'studio', "La «catena dei perché» come attività."),
 'mappai-causal-core.js': ('Studio', [], 'studio', "La logica pura della catena dei perché: nessi presi dai link e dal testo."),
 'mappai-ai-tutor.js': ('Studio', [], 'studio', "Il tutor AI con memoria della conversazione e salvataggio."),
 'mappai-pomodoro.js': ('Studio', [], 'studio', "Il timer Pomodoro e le statistiche di studio."),
 'mappai-garden-core.js': ('Studio', [], 'studio', "La logica pura del Knowledge Garden."),
 'mappai-dungeon-core.js': ('Studio', [], 'studio', "Il validatore dei piani a griglia, resto del Memory Dungeon."),
 'mappai-menu-hubs.js': ('Studio', [], 'sempre', "Gli hub modali del menu rapido: materiali, documenti salvati, gestione grafi."),

 # ── Interfaccia ─────────────────────────────────────────────────
 'mappai-ui-modals.js': ('Interfaccia', [], 'sempre', "Toast, alert, conferme, prompt, modale di configurazione AI, scelta del modello."),
 'mappai-modal.js': ('Interfaccia', [], 'sempre', "Il motore dei modali: un modale si dichiara come dati e lo disegna lui."),
 'mappai-modal-core.js': ('Interfaccia', [], 'sempre', "La logica pura dei modali, senza DOM."),
 'mappai-cabina.js': ('Interfaccia', [], 'sempre', "La console «Cabina»: configurazione AI, guida, aspetto, io e l'app."),
 'mappai-console-bento.js': ('Interfaccia', [], 'sempre', "Il cablaggio bento delle console."),
 'mappai-console-manifesto.js': ('Interfaccia', [], 'sempre', "Il comportamento che la veste manifesto chiede alle console."),
 'mappai-costruisci-manifesto.js': ('Interfaccia', [], 'generazione', "COSTRUISCI nella veste manifesto: il mega-bento della generazione."),
 'mappai-bento-composizione.js': ('Interfaccia', [], 'sempre', "La composizione dei box del bento."),
 'mappai-stile-manifesto.js': ('Interfaccia', [], 'sempre', "I pezzi di stile della veste manifesto."),
 'mappai-font.js': ('Interfaccia', [], 'sempre', "Il carattere dell'app, applicato alla pagina e ai PDF."),
 'mappai-font-core.js': ('Interfaccia', [], 'sempre', "Il catalogo dei caratteri, in un posto solo."),
 'mappai-a11y.js': ('Accessibilità', [], 'sempre', "Gli strumenti compensativi: sillabazione, interlinea, zoom del testo."),
 'mappai-tts-reader.js': ('Accessibilità', [], 'sempre', "La lettura ad alta voce con la barra di controllo."),

 # ── Costi e dev ─────────────────────────────────────────────────
 'mappai-usage-tracker.js': ('Costi e dev', [7,2], 'sempre', "Il tracker dei consumi lato pagina: ogni chiamata viene taggata e contata."),
 'mappai-usage-core.js': ('Costi e dev', [7], 'sempre', "La logica pura del registro consumi: token, costi, categorie."),
 'mappai-usage-dashboard.js': ('Costi e dev', [7], 'sempre', "Il cruscotto dei consumi: quanto è costata ogni cosa."),
 'dev-console-metrics.js': ('Costi e dev', [7,9], 'dev', "Il toolkit da console: metriche della mappa e interruttori delle fasi."),
 'mappai-dev-selftest.js': ('Costi e dev', [9], 'dev', "Il pannello che verifica a runtime che gli agganci ci siano ancora."),
}
