name: Build/Release
on:
  push:
    branches:
      - MappAI_main
      - MappAI_studente
      - global
      - MappAI_iPad
      - MappAI_iPad_studente
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            platform: win
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npx electron-builder --${{ matrix.platform }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Upload Artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: installers-${{ matrix.platform }}
#          path: |
#            dist/*.exe
#            dist/*.dmg
#            dist/*.AppImage
#            dist/*.deb
#          if-no-files-found: error
